### PR TITLE
Adding top-level libary API

### PR DESCRIPTION
**Pull request by mwalkerwells**
Allows for...
```purescript
import Type.Data.Peano (kind Int)
```

Working on https://github.com/purescript/package-sets/pull/588

### CODE REVIEW

**Comment by csicar** [comment]
Yes, that's a good idea. I'm happy to merge that.

The addition of purty to package-lock.json seems unrated to this PR. Could you remove that change?

**Comment by mwalkerwells** [comment]
Ah, yeah, may bad. Removed.

**Comment by mwalkerwells** [comment]
Could we bump the version too?

**Comment by csicar** [comment]
I dumped the version to `0.1.7` https://pursuit.purescript.org/packages/purescript-typelevel-peano/0.1.7/

**Comment by csicar** [comment]
While updating the README, I also found some problems with parsing from a Symbol.

I bumped the version again to include those fixes. The new version is `0.1.8`
`NProxy` and `IProxy` now also have a constructor, so no weird stuff with `undefined` is necessary anymore (`NProxy :: NProxy D10` replaces `undefined :: NProxy 10`

**Comment by mwalkerwells** [comment]
Great, I just updated the package-set PR

**Pull request merged**
